### ISSUE TITLE
Improve the CI tests

### ISSUE THREAD

**Issue by mtulio** [truly-systems/glpi-sdk-python#6]
We could improve the CI tests as a follows:
- Create an "mock" API to test the SDK; OR
- Create an environment in [TravisCI](https://travis-ci.org/glpi-project/glpi) like [the official project does](https://github.com/glpi-project/glpi/blob/9.1/bugfixes/.travis.yml).
Improve the CI tests using the real

**Comment by poikilotherm** [comment]
Whoops... I really overlooked this before I opened #19, which is kind of a third way. Sorry!

The reason to go that path was to configure the REST api, etc, because `cliinstall.php` or some other tool is not doing this for us. I made a DB dump after the configuration and import this anytime the container is built.

Maybe this could be extended by letting `create_bigdump.php` run at build time, or, of this takes to long in means of build time, create a dump to import after running this one time. (And maybe that bigdump should be shrinked a bit, as for testing the SDK it is not necessary to have a giant database around...)

**Comment by mtulio** [comment]
Dup of #19 . Thanks @poikilotherm to the improvement in CI tests. I agree with you that some tests is useless, but in that time I needed to write a lot of deps (Dockerfiles, etc) that was not the goal in that time, but giving more functionality in SDK.

You did a good job writing a compose file, I opended an PR to check current images and join with your improvements and suggestions. :+1
